fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/utdanning/vurdering
    password:
    username:
    #base-url: http://localhost:8081
    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      elevfravar:
        domain-name: utdanning
        package-name: vurdering
        resource-name: elevfravar
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      fravarsoversikt:
        domain-name: utdanning
        packageName: vurdering
        resource-name: fravarsoversikt
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE
      samtykke:
        domain-name: personvern
        packageName: samtykke
        resource-name: samtykke
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter



